version: '3.8'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"  
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_pass
    volumes:
      - db_volume:/var/lib/mysql 
    networks:
      - wp_network

  wordpress:
    image: wordpress:latest
    depends_on:
      - db 
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db:3306 
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_pass
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - wordpress_volume:/var/www/html 
    networks:
      - wp_network

volumes:
  db_volume:
  wordpress_volume: 

networks:
  wp_network:
    driver: bridge