version: '3.8'
services:
  app:
    build: ./app  
    ports:
      - "3000:3000" 
    depends_on:
      mongo:
        condition: service_healthy 
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb  
    networks:
      - app_network

  mongo:
    image: mongo:latest  
    ports:
      - "27017:27017"  
    volumes:
      - mongo_data:/data/db  
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping').ok"]  
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

volumes:
  mongo_data:  

networks:
  app_network:  
    driver: bridge