version: '3.8'

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-express-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    restart: always