version: '3'
services:
  db:
    image: mysql:8.0           
    environment:
      MYSQL_USER: user         
      MYSQL_PASSWORD: password 
      MYSQL_DATABASE: mydb     
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"            