version: '3.8'
services:
  flask1:
    build: ./flask  
    expose:
      - "5000"  
    networks:
      - app_network

  flask2:
    build: ./flask  
    expose:
      - "5000"  
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"  
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  
    depends_on:
      - flask1
      - flask2
    networks:
      - app_network

networks:
  app_network:  
    driver: bridge