version: '3.8' 
services:
  db-wordpress:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql 

  wordpress:
    image: bitnami/wordpress:6.3.1
    depends_on:
      - db-wordpress
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db-wordpress:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html 

volumes:
  db_data:  # Khai báo volume cho MySQL
  wordpress_data:  # Khai báo volume cho WordPress